# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Simone Ragoni/alice/CTPv15/ctp3-fw-ctpreadout-simulations/project_1.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt.xci
# IP: The module: 'dc_fifo_gbt2olt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Simone Ragoni/alice/CTPv15/ctp3-fw-ctpreadout-simulations/project_1.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt.xdc
# XDC: The top module name and the constraint reference have the same name: 'dc_fifo_gbt2olt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Simone Ragoni/alice/CTPv15/ctp3-fw-ctpreadout-simulations/project_1.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dc_fifo_gbt2olt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Simone Ragoni/alice/CTPv15/ctp3-fw-ctpreadout-simulations/project_1.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dc_fifo_gbt2olt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Simone Ragoni/alice/CTPv15/ctp3-fw-ctpreadout-simulations/project_1.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt.xci
# IP: The module: 'dc_fifo_gbt2olt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Simone Ragoni/alice/CTPv15/ctp3-fw-ctpreadout-simulations/project_1.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt.xdc
# XDC: The top module name and the constraint reference have the same name: 'dc_fifo_gbt2olt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Simone Ragoni/alice/CTPv15/ctp3-fw-ctpreadout-simulations/project_1.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dc_fifo_gbt2olt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Simone Ragoni/alice/CTPv15/ctp3-fw-ctpreadout-simulations/project_1.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dc_fifo_gbt2olt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
