######################################################################
#
# File name : IR_tb.udo
# Created on: Fri Jun 24 14:12:38 +0200 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
