######################################################################
#
# File name : IR_tb_wave.do
# Created on: Fri Jun 24 14:12:38 +0200 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
